version: '3.8'

services:
  # PostgreSQL データベース
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: claude_db
      POSTGRES_USER: claude_user
      POSTGRES_PASSWORD: claude_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude_user -d claude_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # バックエンド (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://claude_user:claude_password@db:5432/claude_db
      - SECRET_KEY=your-secret-key-here
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=claude_db
      - POSTGRES_USER=claude_user
      - POSTGRES_PASSWORD=claude_password
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # フロントエンド (Vue.js) - 開発時のみ
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev

volumes:
  postgres_data: